working fall-through algorithm
macmillancontentscience/morphemepiece pull request #1
Opened 2021-02-15 16:48 UTC by jonathanbratt

it's not pretty, and it's slow.

2021-02-15 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/macmillancontentscience/morphemepiece?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/macmillancontentscience/morphemepiece?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/macmillancontentscience/morphemepiece?pullRequest=1) it.</sub>

2021-02-15 23:09 UTC, jonthegeek requested changes
I'll approve this with a couple tweaks, but I definitely think we should try a couple more iterations of ways to do this. It feels like it HAS to be possible to (drastically) simplify.

2021-02-15 23:09 UTC, jonthegeek commented on R/morphemepiece.R
> +    if (stringr::str_starts(word, pattern = "##", negate = TRUE)) {
Simplify:
`valid_start <- stringr::str_starts(word, pattern = "##", negate = TRUE)`

2021-02-16 16:04 UTC, jonathanbratt commented on R/morphemepiece.R
> +    if (stringr::str_starts(word, pattern = "##", negate = TRUE)) {
good call!

2021-02-16 18:14 UTC, jonathanbratt commented on R/morphemepiece.R
> +#' @keywords internal
exporting a wrapping function, as per conversation.

2021-02-16 18:22 UTC, jonthegeek approved these changes
I can't undo my comment about the pipe, but obviously that's fine now (I think it MIGHT have gone away since the code it was attached to is gone now). Obviously this will need work, but woot to having a thing!

2021-02-16 18:22 UTC, jonthegeek commented on R/morphemepiece.R
>  NULL
Let's start using the more-correct import methodology:

```
#' @importFrom magrittr %>%
magrittr::`%>%`
```

2021-02-16 18:22 UTC, jonthegeek commented on R/morphemepiece.R
> +        dplyr::mutate(which_wp = dplyr::row_number()) %>%
Good catch!

2021-02-16 18:22 UTC, merged